export const GET_CATS_REQUEST = 'GET_CATS_REQUEST';
export const GET_CATS_SUCCESS = 'GET_CATS_SUCCESS';
export const GET_CATS_FAILURE = 'GET_CATS_FAILURE';
export const UPDATE_RANKING = 'UPDATE_RANKING';
export const GET_RANKING_SUCCESS = 'GET_RANKING_SUCCESS';